CREATE TABLE Borrowers(
NAME varchar(50) NOT NULL,
ADDRESS	VARCHAR(50) NOT NULL,
STUDENT_NUMBER INT NOT NULL,
TITLE VARCHAR(50) UNIQUE,
AUTHOR VARCHAR(50) NOT NULL,
DATE_BORROWED Date not null,
DATE_DUE DATE NOT NULL,
);